name: Release on Version
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: App Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      statuses: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Determine Image Tags
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{github.repository}}
          tags: |
            latest
            ${{github.ref_name}}
            ${{github.sha}}
      - name: Build Docker image (without pushing)
        id: build
        uses: docker/build-push-action@v6
        with:
          context: ./juice-shop-master/
          file: ./juice-shop-master/Dockerfile
          platforms: linux/amd64
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            local-scan:latest
            ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}:${{ github.sha }}
          format: "sarif"
          output: "trivy-results.sarif"
          severity: "CRITICAL,HIGH"
          exit-code: "1" # Fail the step if vulnerabilities are found

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() # Always upload results even if Trivy scan fails
        with:
          sarif_file: "trivy-results.sarif"

      - name: Push Docker image (only if scan passes)
        if: success() # Only runs if all previous steps succeeded
        uses: docker/build-push-action@v6
        with:
          context: ./juice-shop-master/
          file: ./juice-shop-master/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
